[theme]

# Primary accent for interactive elements
primaryColor = "008080"

# Background color for the main content area
backgroundColor = "#111111"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#393939"


#Color used for almost all text
textColor = "#fafafa"

# Font family for all text in the app
# Default: "sans serif"
font="sans serif"

[server]
enableStaticServing = true
